 task-5
name: Task 5 - Model Training
on: push

name: Credit Risk CI Pipeline

on:
  push:
    branches:
      - main
      - task-1
      - task-2
      - task-3
      - task-4   # added task-4
  pull_request:
    branches:
      - main
      - task-1
      - task-2
      - task-3
      - task-4   # added task-4
 main

jobs:
  task5:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install Task 5 packages
        run: pip install mlflow scikit-learn pandas
        
      - name: Mark completion
        run: echo "âœ… Task 5 workflow passed"